### ISSUE TITLE
question: clipperhouse & gen

### ISSUE THREAD

**Issue by gedw99** [ahmetalpbalkan/go-linq#13]
Hello. I stil getting into go and learning. I used to do OOP languages, so excuse the newbie questions.
This is really nice to see in Golang.

Does this  generate at design time ?

Have you thought about design time using clipperhouse gen ?

Have you thought about an JSON like definition of the data types, and gen the types and then gen the query layer ?

**Comment by ahmetalpbalkan** [comment]
@gedw99 Hi! This project does not do code generation. I thought about that and decided to go with this model since clipperhouse/gen was doing code generation already. I personally find this model more flexible and easily modifiable although this is less type-safe.
