### ISSUE TITLE
FAQ addition:

### ISSUE THREAD

**Issue by 0xor1** [ahmetalpbalkan/go-linq#24]
could a question and (hopefully an answer) be added to the FAQ along the lines of: "Are linq result slices guaranteed to be assigned new underlying arrays to avoid any memory management issues?"

**Comment by ahmetalpbalkan** [comment]
Agreed. We don't modify user input slices/maps and we don't modify the slices/maps we return afterwards... Would you like to contribute this?



— Ahmet Alp Balkan http://alp.im

**Comment by 0xor1** [comment]
added the Q&A, I hope I interpreted your comment correctly.

**Comment by ahmetalpbalkan** [comment]
LGTM thanks.
