### ISSUE TITLE
Have Results() return a slice of the original type.

### ISSUE THREAD

**Issue by bsht** [ahmetalpbalkan/go-linq#28]
Currently `Results()` returns a slice of `[]T` where perhaps a way to get the "original" type of the elements would be more convenient. I constantly find myself having to iterate over the `[]T` to copy all elements to a new slice.

    x, err := linq.From(f.Films).Where(func(x linq.T) (bool, error) { return true, nil }).Results()
    if err != nil {
     fmt.Println(err)
    }

Here `x` is of type `[]T` and so I cannot reassign it to `f.Films`. I need to do the following:

    f.Films = make([]Film, len(x))
    for i, b := range x {
     f.Films[i] = b.(Film)
    }

I find myself doing this kind of thing very often when using your package. Perhaps there should be a way to do this included in the package itself?

**Comment by ahmetalpbalkan** [comment]
It is technically not possible to return a `[]Film` from the `Results()` method due to type system restrictions in Go language. There are similar packages such as https://clipperhouse.github.io/gen/ that generate code for your types, which can achieve what you want.
