### ISSUE TITLE
custom query functions - mean, median

### ISSUE THREAD

**Issue by siddharth178** [ahmetalpbalkan/go-linq#29]
First of all, thanks for simple and super useful library!!

Only thing I would like to see added is a way to add custom functions like Average. I know there are multiple functions readily available, but what if I want to do Mean, Median or some kind of custom processing on values. It doesn't expose values to outside world as well. So kind of feels restricted.

If you have any thoughts on this, please share, I can try implementing it.

**Comment by kalaninja** [comment]
It is possible to do now. Look the readme.

**Comment by siddharth178** [comment]
Thanks a lot. I will give it a try.
