### ISSUE TITLE
using semantic versioning

### ISSUE THREAD

**Issue by aisk** [ahmetalpbalkan/go-linq#36]
Can we use a [semver](http://semver.org/) instead of current v`x.y` versioning, for better third party packaging usage?

Now I have a project using [glide](http://glide.sh/) to manage third party deps. And glide will recognize semver if a repo have tags like `v2.0.0` like [this](https://github.com/tj/go-debug), and I can keep using a specified major version of package per build, and it wouldn't break my codes. 

I think it's much cooler if `go-linq` use semver 😎

**Comment by ahmetalpbalkan** [comment]
@aisk we're about to tag a `v2.0.0.beta1`. hang tight and let us know if you run into any issues.

**Comment by ahmetalpbalkan** [comment]
I just tagged `v2.0.0-rc0` if we don't hear any issues, we'll tag it as `v2.0.0` soon.

cc: @kalaninja

**Comment by aisk** [comment]
Thank you @ahmetalpbalkan !
