### ISSUE TITLE
v3: benchmark_test.go

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ahmetalpbalkan/go-linq#48]
@cleitonmarx are we actually using this `benchmark_test.go` file in v3-dev branch?

It looks like our travis-CI tests are not executing it. I just got this output:

```
$ go test -bench . .
BenchmarkSelectWhereFirst-4            	 5000000	       323 ns/op
BenchmarkSelectWhereFirst_generics-4   	 1000000	      1959 ns/op
BenchmarkSum-4                         	      30	  46626334 ns/op
BenchmarkSum_generics-4                	       3	 468433125 ns/op
BenchmarkZipSkipTake-4                 	 5000000	       301 ns/op
BenchmarkZipSkipTake_generics-4        	 1000000	      1557 ns/op
PASS
ok  	github.com/ahmetalpbalkan/go-linq	12.279s
```

Is there a reason for this to stay in the repo? We can perhaps make it a bit more detailed (such as specify input sizes) and still keep it in the package?

**Comment by cleitonmarx** [comment]
@ahmetalpbalkan The initial idea was to compare performance between typed and regular functions. I copied the code used by @kalaninja to compare performance between v0.9 and v2.0.

**Comment by ahmetalpbalkan** [comment]
OK we can keep it.
